version: "3.7"
services:
  # Redis
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379" # Port not binded, available through hostname inside network
    networks:
      - product

  db:
    image: postgres:9.6
    restart: always
    environment: 
      POSTGRES_PASSWORD: postgrepass
      POSTGRES_USER: postgreuser
      POSTGRES_DB: postgredb
    volumes:
      - postgredb:/var/lib/postgresql/data
    networks:
      - product
  # Adminer for Postgre DB Managment
  adminer:
    image: adminer
    restart: always
    ports:
      - "8088:8080"

  influxdb:
    image: influxdb:alpine
    restart: always
    ports:
      - "8086:8086"  #HTTP API-PORT can be not binded to external
      - "2003:2003"  #Graphite PORT if is Enabled
    environment: 
      INFLUXDB_HTTP_AUTH_ENABLED: 'true' # If not set users won't be created ad admin initialization
      INFLUXDB_GRAPHITE_ENABLED: 'false'
      # Used for db initialization
      INFLUXDB_DB: 'db0' 
      INFLUXDB_ADMIN_USER: 'admin' 
      INFLUXDB_ADMIN_PASSWORD: 'supersecretpassword'
      INFLUXDB_USER: 'telegraf'
      INFLUXDB_USER_PASSWORD: 'secretpassword'
    networks:
      - product
    volumes:
      - influxdb:/var/lib/influxdb

  # Chronograf is the new influx dashboard
  chronograf:
    image: chronograf
    restart: always
    ports: 
      - 8888:8888
    depends_on:
      - influxdb
    networks:
      - product
    command: chronograf --influxdb-url=http://influxdb:8086

  # django:
  #   image: somedjangoimage
  #   restart: always
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - product
  #   depends_on:
  #     - db


  # celary:
  #   image: someceleryimage
  #   restart: always
  #   networks:
  #     - product
  #   depends_on:
  #     - db

networks:
  product:

volumes:
  postgredb:
  influxdb: